# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .nested_component import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "provider-nested",
  "mod": "index",
  "fqn": "julienp_test_org_provider_nested",
  "classes": {
   "provider-nested:index:NestedComponent": "NestedComponent"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "provider-nested",
  "token": "pulumi:providers:provider-nested",
  "fqn": "julienp_test_org_provider_nested",
  "class": "Provider"
 }
]
"""
)
